var searchData=
[
  ['system_20ahb_20and_20apb_20busses_20clocks_20configuration_20functions',['System AHB and APB busses clocks configuration functions',['../group___r_c_c___group2.html',1,'']]],
  ['spi',['SPI',['../group___s_p_i.html',1,'']]],
  ['spi_5fbaudrate_5fprescaler',['SPI_BaudRate_Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_5fclock_5fphase',['SPI_Clock_Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_5fclock_5fpolarity',['SPI_Clock_Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_5fcrc_5fpolynomial',['SPI_CRC_polynomial',['../group___s_p_i___c_r_c__polynomial.html',1,'']]],
  ['spi_5fcrc_5ftransmit_5freceive',['SPI_CRC_Transmit_Receive',['../group___s_p_i___c_r_c___transmit___receive.html',1,'']]],
  ['spi_5fdata_5fdirection',['SPI_data_direction',['../group___s_p_i__data__direction.html',1,'']]],
  ['spi_5fdata_5fsize',['SPI_data_size',['../group___s_p_i__data__size.html',1,'']]],
  ['spi_5fdirection_5ftransmit_5freceive',['SPI_direction_transmit_receive',['../group___s_p_i__direction__transmit__receive.html',1,'']]],
  ['spi_5fexported_5fconstants',['SPI_Exported_Constants',['../group___s_p_i___exported___constants.html',1,'']]],
  ['spi_5fi2s_5faudio_5ffrequency',['SPI_I2S_Audio_Frequency',['../group___s_p_i___i2_s___audio___frequency.html',1,'']]],
  ['spi_5fi2s_5fclock_5fpolarity',['SPI_I2S_Clock_Polarity',['../group___s_p_i___i2_s___clock___polarity.html',1,'']]],
  ['spi_5fi2s_5fdata_5fformat',['SPI_I2S_Data_Format',['../group___s_p_i___i2_s___data___format.html',1,'']]],
  ['spi_5fi2s_5fdma_5ftransfer_5frequests',['SPI_I2S_DMA_transfer_requests',['../group___s_p_i___i2_s___d_m_a__transfer__requests.html',1,'']]],
  ['spi_5fi2s_5fflags_5fdefinition',['SPI_I2S_flags_definition',['../group___s_p_i___i2_s__flags__definition.html',1,'']]],
  ['spi_5fi2s_5finterrupts_5fdefinition',['SPI_I2S_interrupts_definition',['../group___s_p_i___i2_s__interrupts__definition.html',1,'']]],
  ['spi_5fi2s_5flegacy',['SPI_I2S_Legacy',['../group___s_p_i___i2_s___legacy.html',1,'']]],
  ['spi_5fi2s_5fmclk_5foutput',['SPI_I2S_MCLK_Output',['../group___s_p_i___i2_s___m_c_l_k___output.html',1,'']]],
  ['spi_5fi2s_5fmode',['SPI_I2S_Mode',['../group___s_p_i___i2_s___mode.html',1,'']]],
  ['spi_5fi2s_5fstandard',['SPI_I2S_Standard',['../group___s_p_i___i2_s___standard.html',1,'']]],
  ['spi_5fmode',['SPI_mode',['../group___s_p_i__mode.html',1,'']]],
  ['spi_5fmsb_5flsb_5ftransmission',['SPI_MSB_LSB_transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_5fnss_5finternal_5fsoftware_5fmanagement',['SPI_NSS_internal_software_management',['../group___s_p_i___n_s_s__internal__software__management.html',1,'']]],
  ['spi_5fprivate_5ffunctions',['SPI_Private_Functions',['../group___s_p_i___private___functions.html',1,'']]],
  ['spi_5fslave_5fselect_5fmanagement',['SPI_Slave_Select_management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['stm32f4xx_5fstdperiph_5fdriver',['STM32F4xx_StdPeriph_Driver',['../group___s_t_m32_f4xx___std_periph___driver.html',1,'']]],
  ['smartcard_20mode_20functions',['Smartcard mode functions',['../group___u_s_a_r_t___group6.html',1,'']]]
];
