

	// macros
	#define K_UNUSED(param) (void)param
	#define K_PERFORMANCE(operating_function,result) \
	result = kSystem.micros();\
	operating_function;\
	result -= kSystem.micros()



	#define kMACRO_GET_PIN_ATTRIBUTE(c,d) 0x000000##c##d
	#define kMACRO_GET_PORT_STRING(name,pin) PORT##name##pin
	#define kMACRO_GET_PORT_PIN_ENUM(name,pin,pV,piV) kMACRO_GET_PORT_STRING(name,pin)\
		=kMACRO_GET_PIN_ATTRIBUTE(pV,piV) \


	#define kMACRO_GET_PORT_16PINS_ENUM(PORT_INDEX,PORT_VALUE) \
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,0,PORT_VALUE,0),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,1,PORT_VALUE,1),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,2,PORT_VALUE,2),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,3,PORT_VALUE,3),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,4,PORT_VALUE,4),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,5,PORT_VALUE,5),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,6,PORT_VALUE,6),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,7,PORT_VALUE,7),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,8,PORT_VALUE,8),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,9,PORT_VALUE,9),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,10,PORT_VALUE,A),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,11,PORT_VALUE,B),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,12,PORT_VALUE,C),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,13,PORT_VALUE,D),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,14,PORT_VALUE,E),\
		kMACRO_GET_PORT_PIN_ENUM(PORT_INDEX,15,PORT_VALUE,F)\

	#define kMACRO_GET_ALL_PORTS_PINS_ENUM \
		kMACRO_GET_PORT_16PINS_ENUM(A,0),\
		kMACRO_GET_PORT_16PINS_ENUM(B,1),\
		kMACRO_GET_PORT_16PINS_ENUM(C,2),\
		kMACRO_GET_PORT_16PINS_ENUM(D,3),\
		kMACRO_GET_PORT_16PINS_ENUM(E,4),\
		kMACRO_GET_PORT_16PINS_ENUM(F,5),\
		kMACRO_GET_PORT_16PINS_ENUM(G,6),\
		kMACRO_GET_PORT_16PINS_ENUM(H,7),\
		kMACRO_GET_PORT_16PINS_ENUM(I,8)\


#define kMACRO_GET_DRIVE_RESULT_ENUM \



